main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views

from django.contrib.auth import views as auth_views

urlpatterns = [
  path('', views.index_page),
  path("custommaps/", views.custommaps),
  path("create_custommaps/", views.create_custommaps),
  path("custom_maps/<title>/", views.custommaps_detail),

  path('projects/', views.projects),
  path('create_project/', views.create_project),
  path('projects/<title>', views.project_detail),
  path('projects/<title>/view/', views.project_view),
  path('project/export/<title>/', views.project_view_export),
  path('project_categories/<title>', views.project_categories),

  path('project/add_category', views.add_category),
  path('project/add_sub_category', views.add_sub_category),
  path('project/add_sub_category', views.add_sub_category),
  path('project/get_categories', views.get_categories),
  path('project/export_project/<project_id>', views.export_project),
 

  # pins
  path("pins/", views.get_pins),
  path("pins/create", views.create_pins),
  path("pins/update_pin/<pin_pk>", views.update_pin_details),
  path('pins/delete/<title>', views.delete_pins),

  # icons
  path("icons", views.icons_list),
  path("icons_list/", views.get_icons),

  # user acc
  # path("accounts/login/", auth_views.LoginView.as_view(template_name="accounts/login.html")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapmk/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('',include("main.urls"),name="main"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('i18n/', include('django.conf.urls.i18n')), 
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
TILES_OPTIONS = (
    (),
    ()
)

default_user = User.objects.get(id=1)

class CustomMaps(models.Model):
    title = models.CharField(max_length=200,null=False, unique=True)
    description = models.TextField(blank=True, null=True)
    tiles_folder = models.CharField(default="/media/uploads/projects/efteling", max_length=400)
    center = models.CharField(max_length=200, default="0,0", null=False)
    tiles_in_folders = models.BooleanField(default=False)
    is_osm_based_map = models.BooleanField(default=False)
    map_style_url = models.CharField(blank=True, null=True, max_length=500)
    thumbnail = models.ImageField(upload_to="./uploads/thumbnails/custommaps/")
    bearing = models.IntegerField(default=0, null=False)
    minzoom = models.IntegerField(default=0)
    maxzoom = models.IntegerField(default=5)
    mobile_minzoom = models.IntegerField(default=5)
    # tileSize = models.IntegerField(default=256)

    class Meta:
        verbose_name_plural = "Custom Maps"

    def __str__(self):
        return self.title

READING_MODES = (
    ("RTL", "Right To Left"),
    ("LTR", "Left To Right")
)

PROJECT_LANG = (
    ("en", "English"),
    ("ar", "Arabic"),
    ("he", "Hebrew"),
)

DEFAULT_STYLESHEET = """
    --project-font:Alef, Poppins !important;
    --project-font-he:Poppins, Alef !important;
    --project-font-ar:Poppins, Alef !important;

    --simple-text-size:12;
    --simple-text-offset:1;
    --area-text-size:15;
    --area-text-offset:3.2;
    --simple-text-minzoom:14;
    --simple-icon-minzoom:14;
    --area-icon-minzoom:17;

    --canvas-bg-color:#000000;

    --area-text-color:#ffffff;
    --simple-text-color:#000;
    --circle-icon-color:#ff75f4;
    --circle-icon-stroke-color:#151818;
    --filter-bg-color:#2a3944;
    --icons-bg:#2a3944;
    --infobox-bg:#ffffff;
    --infobox-text-color:#1b0f23;
    --infobox-title-font-size:26px;
    --infobox-subtitle-font-size:18px;
    --infobox-font-size:13px;
    --filter-icon-size:35px;

    --text-color:#d6f8ff;
    --filter-card-active:#364a57;
    --filter-card-active-text-color:#ff75f4;
    --filter-card-line-color:#78a5be;

    --accept-button-bg-color:#af349b;
    --accept-button-text-color:#d6f8ff;
    --close-button-bg-color:#616c75;
    --close-button-text-color:#d6f8ff;
"""

# 1 for the filters windows background, 
# 1 for the icons bg, 
# 1 for the infobox backgroud, 
# 1 for the texts,
#  1 for the chosen area around texts on filters menu
INFOBOX_TYPES = (
    ("Default", "Default"),
    ("Aside", "Side Infobox")
)

class Project(models.Model):
    title = models.CharField(max_length=200,null=False)
    project_owner = models.ForeignKey(User, on_delete=models.CASCADE, default=default_user.pk)
    custom_map = models.ForeignKey(CustomMaps, on_delete=models.SET_NULL, null=True)
    project_language = models.CharField(choices=PROJECT_LANG, default="en", max_length=50)
    project_theme = models.TextField(default=DEFAULT_STYLESHEET, max_length=4100)
    infobox_style = models.CharField(max_length=100, choices=INFOBOX_TYPES, default="Default")

    class Meta:
        verbose_name_plural = "Projects"
    
    def __str__(self):
        return self.title

ICON_TYPES = (
    ("Pin", "Pin Icon"),
    ("Area", "Area Icon"),
    ("Accesibility", "Accessibility Icon")
)

class Icons(models.Model):
    title = models.CharField(max_length=200,null=False)
    icon_type = models.CharField(max_length=100, choices=ICON_TYPES, default="Pin")
    icon = models.FileField(upload_to="./uploads/icons/")

    class Meta:
        verbose_name_plural = "Icons"

    def __str__(self):
        return self.title

def content_file_name(instance, filename):
    folder_path = '/'.join(["uploads/icons/", instance.project.title,  filename])
    return folder_path

class PinCategory(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    title = models.CharField(default="", max_length=200)
    icon = models.FileField(upload_to=content_file_name, default="uploads/icons/axe_active.png")
    is_area_category = models.BooleanField(default=False)
    is_simple_icon = models.BooleanField(default=False)
    active_icon = models.FileField(upload_to=content_file_name, default="uploads/icons/axe_active.png")
    ranking_value = models.IntegerField(default=0, )

    class Meta:
        verbose_name_plural = "Pin Categories"

    def __str__(self):
        return self.title

class PinSubCategory(models.Model):
    category = models.ForeignKey(PinCategory, on_delete=models.SET_NULL, null=True)
    title = models.CharField(default="", max_length=200)

    class Meta:
        verbose_name_plural = "Pin Sub Categories"    

    def __str__(self):
        return self.title

PIN_TYPES = (
    ("Area Pin", "Area Pin"),
    ("Detail Pin", "Detail Pin"),
    ("Simple Icon", "Simple Icon"),
    ("Simple Text", "Simple Text"),
)

def pin_file_name(instance, filename):
    folder_path = '/'.join(["uploads/thumbnails/", instance.project.title,  filename])
    return folder_path

class Pins(models.Model):
    title = models.CharField(max_length=200,null=False)
    subtitle =models.CharField(max_length=200, blank=True)
    pin_type = models.CharField(max_length=100, choices=PIN_TYPES, default="Detail Pin")
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    description = models.TextField(null=True, blank=True)
    category = models.CharField(null=False, max_length=100, default="Attraction")
    subcategory = models.CharField(null=True, max_length=100, blank=True)
    icon = models.CharField(null=False, max_length=1000)
    active_icon = models.CharField(null=False, max_length=1000, default="uploads/icons/axe_active.png")
    maxzoom = models.IntegerField(default=18)
    minzoom = models.IntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    location_image = models.ImageField(default="default.png", upload_to=pin_file_name)
    accesibility_features = models.JSONField(null=True)
    more_info_link = models.CharField(null=True, blank=True, max_length=350)
    is_simple_pin = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Pins"

    def __str__(self):
        return self.title

templates/base.html
{% load i18n %}
{% load static %}
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            {% translate "Wayfinding Map" %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">


    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>


        @font-face {
            font-family:'IBMPlexSans-Bold';
            font-weight: bold;
            font-style: normal;
            src: url({% static 'fonts/IBMPlexSans-Bold.ttf' %});
        }

        @font-face {
            font-family:'IBMPlexSansHebrew-Bold';
            font-weight: bold;
            font-style: normal;
            src: url({% static 'fonts/IBMPlexSansHebrew-Bold.ttf' %});
        }

        @font-face {
            font-family:'IBMPlexSansArabic-Bold';
            font-weight: bold;
            font-style: normal;
            src: url({% static 'fonts/IBMPlexSansArabic-Bold.ttf' %});
        }

        @font-face {
            font-family:'NarkissTam-Bold';
            font-weight: bold;
            font-style: normal;
            src: url({% static 'fonts/NarkissTam-Bold.otf' %});
        }

        @font-face {
            font-family:'Advertising-Bold';
            font-weight: bold;
            font-style: normal;
            src: url({% static 'fonts/Advertising-Bold.otf' %});
        }


        @font-face {
            font-family:'Gill Sans Bold';
            font-weight: bold;
            font-style: normal;
            src: url({% static 'fonts/Gill Sans Bold.otf' %});
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block header %}
    {% endblock %}
</head>
<body>


    <form action="{% url 'set_language' %}" method="post" class="d-none" id="lang-form">{% csrf_token %}
        <div class="d-none"></div>
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <select name="language" id="lang-div">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="Go" id="lang-submit">
    </form>



        <div class="lang-toggle">
            <select name="lang-select" id="lang-select" class="form-control" style="font-size: 10px;">
                <option value="en" {% if "en" == LANGUAGE_CODE %} selected{% endif %}>Engilsh</option>
                <option value="he" {% if "he" == LANGUAGE_CODE %} selected{% endif %}>Hebrew</option>
                <option value="ar" {% if "ar" == LANGUAGE_CODE %} selected{% endif %}>Arabic</option>
            </select>
        </div>

    {% block content %}
    {% endblock %}
    <script>
        let lang = {
            'ar':"rtl",
            'en':"ltr",
            'he':"rtl"
        };

        let lang_code = "{{ LANGUAGE_CODE }}"

        let isRtl = true;
        function changeLanguage(langCode) {
            langCode = langCode.toLocaleLowerCase();

            let html  = document.querySelector("html");
            html.dir = lang[langCode];
            html.lang = langCode;

            // document.getElementById("rtl-toggler").innerHTML = lang[langCode];
        }

        let langToggler = document.getElementById("lang-select")
        langToggler.onchange = (e) => {
            changeLanguage(e.target.value);

            // update the page language
            document.getElementById("lang-div").value = e.target.value;
            document.getElementById("lang-submit").click();
        }

        changeLanguage(lang_code);
    </script>

    {% block js %}

    {% endblock %}
    <script src="{% static 'js/color-modes.js' %}"></script>
</body>
</html>

<!-- cnsdrd-map
@{H<OwjO"q8OUn{be$Sbj^v=O^ai3I -->

templates/create_custommap.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header %}
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
 
    <style>
        .main {
            width: 1000px;
            margin: 0 auto;
            display: flex;
        }

        .form-section {
            flex: 1;
        }

        .map-section {
            flex: 0.8;
        }

        .mini-map {
            width: 100%;
            height: 90%;
        }

        @media only screen and (max-width: 480px) { 
            .main {
                width: 90%;
                margin:0 auto;
                flex-direction: column-reverse;
                background-color: #fff;
            }   

            .mini-map {
                height: 180px;
            }
        }
    </style>
{% endblock %}

{% block content %}
{% include "navbar.html" %}
<div class="main mt-5">
    <div class="form-section">
        <form action="" class="mx-3 my-2 form" method="post" id="upload_form">
            <h5>{% translate "Add Custom Map" %}</h5>
            {% csrf_token %}
            {% for field in form %}
                {{ field.errors }}
                <div class="mb-3">
                    <label class="form-label">{% translate field.label %}</label> <br>
                    {{ field }}
                </div>
                
            {% endfor %}

            <div class="mb-3">
                <label for="id_center" class="form-label">{% translate "Center" %}</label> <br>
                <input class="form-control" type="text" name="center" value="0,0" maxlength="200" id="id_center" placeholder="" required>
            </div>
    
            <div class="mb-3">
                <label for="id_tiles" class="form-label">{% translate "Tiles Zip File" %}</label> <br>
                <input class="form-control" type="file" name="tiles" maxlength="200" id="id_tiles" placeholder="Tiles Zip" required>
            </div>
    
            <input type="submit" value="{% translate 'Upload Custom Map' %}" class="btn btn-primary">
        </form>
        <div class="container d-none progress" id="progress"></div>
    </div>

    <div class="map-section mt-3">
        <div class="mb-3">
            <span class="form-label"> {% translate "Click or search to set map center" %}</span> 
        </div>
        <div class="mini-map" id="mini-map"></div>
    </div>    
</div>
    <script>
        const uploadForm = document.getElementById('upload_form');
        const input_file = document.getElementById('id_tiles');
        const progress_bar = document.getElementById('progress');
        const centerInput = document.getElementById("id_center");

        // const tilesInput = document.getElementById("id_tiles");
        const osmBasedMapInput = document.getElementById("id_is_osm_based_map");

        osmBasedMapInput.onclick = (e) => {
            if(e.target.checked) {
                input_file.removeAttribute("required");
            } else {
                input_file.setAttribute("required", "required");                
            }
        }

        
        $("#upload_form").submit(function(e){
            e.preventDefault();
            $form = $(this)
            var formData = new FormData(uploadForm);
            formData.set("center", centerInput.value);

            const media_data = input_file.files[0];
            if(media_data != null){
                console.log(media_data);
                progress_bar.classList.remove("d-none");
            }
            var object = {};
            formData.forEach((value, key) => object[key] = value);
            var json = JSON.stringify(object);
            console.log(json);

            // return;
            $.ajax({
                type: 'POST',
                url:'/create_custommaps/',
                data: formData,
                dataType: 'json',
                beforeSend: function(){

                },
                xhr:function(){
                    const xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener('progress', e=>{
                        if(e.lengthComputable){
                            const percentProgress = (e.loaded/e.total)*100;
                            console.log(percentProgress);
                            progress_bar.innerHTML = `<div class="progress-bar progress-bar-striped bg-success" 
                    role="progressbar" style="width: ${percentProgress}%" aria-valuenow="${percentProgress}" aria-valuemin="0" 
                    aria-valuemax="100"></div>`
                        }
                    });
                    return xhr
                },
                success: function(response){
                    console.log(response);
                    if(response.data.includes("went wrong")) {
                        console.log(response);
                    } else {
                        uploadForm.reset()
                        progress_bar.classList.add('d-none');
                        window.location.assign("/custommaps/")
                    }
                   
                    // redirect to a project detail page
                    // window.location.assign()
                },
                error: function(err){
                    console.log(err);
                },
                cache: false,
                contentType: false,
                processData: false,
            });
        });

        mapboxgl.accessToken = 'pk.eyJ1IjoiYWFtZXJqYW1lZWwiLCJhIjoiY2xvcnFmemY5MHh0czJqczhlMDZ4cGNnbCJ9.caC-vY545ifokQctbmu0JQ';
        const map = new mapboxgl.Map({
            container: 'mini-map', // container ID
            style: 'mapbox://styles/mapbox/streets-v12',
            center:[5.048771,51.651427],
            zoom: 16
        });

        let geocoder = new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl
        })

        map.addControl(geocoder);
        map.on("load", () => { 
            geocoder.on("result", ({ result}) => {
                let { center } = result;
                document.getElementById("id_center").value = center.join(",");
            });

            map.on("click", (e) => {
                document.getElementById("id_center").value = Object.values(e.lngLat);
            });
        });
</script>
    </script>
{% endblock %}

{% block js %}
<script src="{% static '/js/form-control.js' %}"></script>

{% endblock %}

templates/navbar.html
{% load i18n %}
<div class="header-section">
  <nav class="navbar navbar-expand-lg bg-white w-100" data-bs-theme="light" >
    <div class="container">
      <a class="navbar-brand" href="#">
        {% translate "Wayfinding Map" %}
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" data-bs-theme="light"  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" data-bs-theme="light" ></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"> 
            <a class="nav-link fw-bold py-1 px-0" aria-current="page" href="/">{% translate "Home" %}</a>
          </li>
          

          {% if user.is_authenticated and user.is_superuser %}
            <li class="nav-item"><a class="nav-link fw-bold py-1 px-0" href="/custommaps/">{% translate "Custom Maps" %}</a></li>
            <li class="nav-item"><a class="nav-link fw-bold py-1 px-0" href="/projects">{% translate "Map Projects" %}</a></li>
            <li class="nav-item"> <a class="nav-link fw-bold py-1 px-0" href="/icons">{% translate "Icons" %}</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link fw-bold py-1 px-0" href="/projects">{% translate "My Projects" %}</a></li>
            <li class="nav-item"> <a class="nav-link fw-bold py-1 px-0" href="/icons">{% translate "My Icons" %}</a></li>
          {% endif %}

          <!-- <li class="nav-item"> <a class="nav-link fw-bold py-1 px-0" href="/icons">Categories</a></li> -->
          <li class="nav-item">
            <a class="nav-link fw-bold py-1 px-0" href="/icons"> {{ user.username }}</a>
          </li>
        </ul>

        <div class="navbar-nav">
            {% if user.is_authenticated %}
             <li class="nav-item"> <a href="/accounts/logout" class="nav-link fw-bold py-1 px-0">{% translate "Log Out" %}</a></li>
            {% else %}
              <li class="nav-item"> <a href="/accounts/login" class="nav-link fw-bold py-1 px-0">{% translate "Log In" %}</a> </li>
            {% endif %}
          </div>
        </div>

    </div>
  </nav>  
</div>

templates/project_categories.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header %}
    <style>
        .details-header {
            align-items: center;
            border-bottom: 1px solid #ddd;
            padding:5px;
        }

        .details-header h6 {
            margin:0px;
            margin-left: 10px;
        }

        .main {
            width: 1000px;
            margin: 0 auto;
            display: flex;
        }

        .form-section {
            flex: 0.5;
        }

        .main-section {
            flex: 0.8;
        }

        .mini-map {
            width: 100%;
            height: 90%;
        }

        @media only screen and (max-width: 480px) {
            .main {
                width: 90%;
                margin:0 auto;
                flex-direction: column-reverse;
            }
        }
    </style>
{% endblock %}

{% block content %}
{% include "navbar.html" %}
<div class="main mt-5">
    <div class="main-section">

   
        <div class="map-section mt-3">
            <div class="mb-3">
                <span class="form-label">{% translate "Categories" %}</span> 
            </div>

            <div class="card-section">
                {% for category in categories %}
                    {% if category.is_simple_icon == False %}
                        <div class="details-header d-flex">
                            <img src="/media/{{ category.icon}}" alt="{{ category.title }}" height="25px">
                            <h6 class=""> {{ category.title }}</h6>
                        </div>
                        <div class="body my-3">
                            {% for sub_category in category.pinsubcategory_set.all %}
                                <div>{{  sub_category.title }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>
    
        <div class="map-section mt-3">
            <div class="mb-3">
                <span class="form-label">{% translate "Simple Icons" %}</span> 
            </div>

            <div class="card-section">
                {% for category in categories %}
                    {% if category.is_simple_icon == True %}
                        <div class="details-header d-flex">
                            <img src="/media/{{ category.icon}}" alt="{{ category.title }}" height="25px">
                            <h6 class=""> {{ category.title }}</h6>
                        </div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
        <div class="form-section">
            <form action="" class="mx-3 my-2 form" method="post" id="upload_form">
                <h5>{% translate "Add A Category" %}</h5>
                {% csrf_token %}
                {% for field in category_form %}
                    {{ field.errors }}
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">{% translate field.label %}</label> <br>
                        {{ field }}
                    </div>
                    
                {% endfor %}    
                <input type="submit" value="{% translate 'Add a Category' %}" class="btn btn-primary">
            </form>
            <div class="container d-none progress" id="progress"></div>

            <form action="" class="mx-3 my-2 mt-5 form" method="post" id="sub_category_form">
                <h5>{% translate "Add A Subcategory" %}</h5>
                {% csrf_token %}
                {% for field in sub_category_form %}
                    {{ field.errors }}
                    <div class="mb-3">
                        <label for="" class="form-label">{% translate field.label %}</label> <br>
                        {{ field }}
                    </div>
                    
                {% endfor %}    
                <input type="submit" value="{% translate 'Add Subcategory' %}" class="btn btn-primary">
            </form>
        </div>

        
    {% endif %}
</div>
    <script>
        const uploadForm = document.getElementById('upload_form');
        const input_file = document.getElementById('id_icon');
        const progress_bar = document.getElementById('progress');
        
        $("#upload_form").submit(function(e){
            e.preventDefault();
            $form = $(this)
            var formData = new FormData(this);
            const media_data = input_file.files[0];
            if(media_data != null){
                console.log(media_data);
                progress_bar.classList.remove("d-none");
            }

            $.ajax({
                type: 'POST',
                url:'/project/add_category',
                data: formData,
                dataType: 'json',
                beforeSend: function(){

                },
                xhr:function(){
                    const xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener('progress', e=>{
                        if(e.lengthComputable){
                            const percentProgress = (e.loaded/e.total)*100;
                            console.log(percentProgress);
                            progress_bar.innerHTML = `<div class="progress-bar progress-bar-striped bg-success" 
                    role="progressbar" style="width: ${percentProgress}%" aria-valuenow="${percentProgress}" aria-valuemin="0" 
                    aria-valuemax="100"></div>`
                        }
                    });
                    return xhr
                },
                success: function(response){
                    console.log(response);
                    if(response.data.includes("went wrong")) {
                        console.log(response);
                    } else {
                        uploadForm.reset()
                        progress_bar.classList.add('d-none');
                        window.location.reload();
                    }
                   
                    // redirect to a project detail page
                    
                },
                error: function(err){
                    console.log(err);
                },
                cache: false,
                contentType: false,
                processData: false,
            });
        });

        let subCategoryForm = document.getElementById("sub_category_form");
        $("#sub_category_form").submit(function(e) {
            e.preventDefault();
            let formSubs = document.getElementById("sub_category_form");
            let fD = new FormData(formSubs); 
            console.log("Sub Category");

            $.ajax({
                type: 'POST',
                url:'/project/add_sub_category',
                data: fD,
                dataType: 'json',
                processData: false,
                contentType: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if(response.data.includes("went wrong")) {
                        console.log(response);
                    } else {
                        subCategoryForm.reset()
                        window.location.reload();
                    }
                    
                },
                error: function(err) {
                    console.log(err);
                }
            });


        });
</script>
{% endblock %}

{% block js %}
<script src="{% static '/js/form-control.js' %}"></script>

{% endblock %}